version: '3.1'

services:
  database:
    image: mysql
    container_name: school_MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - school_data:/var/lib/mysql

volumes:
  school_data: